Fixing various issues with loading and help generation with new loader architecture.

diff --git a/bin/core/image b/bin/core/image
--- a/bin/core/image
+++ b/bin/core/image
@@ -7,6 +7,7 @@
 #=========================================================================================
 # Initialization
 #
+set -e
 
 # Initialize top level directories and load bootstrap functions
 SCRIPT_PATH="${BASH_SOURCE[0]}" # bash
@@ -14,13 +15,35 @@ if [[ -z "$SCRIPT_PATH" ]]; then
   SCRIPT_PATH="${(%):-%N}" # zsh
 fi
 
-export __script_name="$(basename "${SCRIPT_PATH//-/ }")"
+export __script_name="reactor reimage"
 export __core_dir="$(cd "$(dirname "${SCRIPT_PATH}")" && pwd)"
 export __bin_dir="$(dirname "${__core_dir}")"
 export __reactor_dir="$(dirname "${__bin_dir}")"
 export __reactor_docker_dir="${__reactor_dir}/docker"
-source "${__core_dir}/env"
+source "${__core_dir}/loader"
 
+warn_no_project
+
+#=========================================================================================
+# Parameter processing
+#
+HELP="Regenerate the local project Reactor virtualization container image"
+
+function image_params () {
+  image_build_options
+}
+parse_cli image_params "$@"
+
+debug "Disable build cache: ${NO_CACHE}"
+
+#========================================
+
+if ! check_project; then
+  add_space
+  error "Active project required to build reactor Docker image."
+  add_space
+  exit 1
+fi
 export REACTOR_IMAGE="${REACTOR_IMAGE:-$APP_NAME}"
 export REACTOR_TAG="${REACTOR_TAG:-"${__reactor_version}"}"
 
@@ -53,7 +76,6 @@ fi
 
 REACTOR_ARGS=(
   "--force-rm"
-  "--no-cache"
   "--file" "${__reactor_docker_dir}/Dockerfile"
   "--tag" "${REACTOR_IMAGE}:${REACTOR_TAG}"
   "--platform" "linux/${__architecture}"
@@ -63,6 +85,10 @@ REACTOR_ARGS=(
   "--build-arg" "REACTOR_USER_UID=${__user_id}"
   "--build-arg" "REACTOR_DOCKER_GID=${__docker_group_id}"
 )
+
+if [ "$NO_CACHE" ]; then
+  REACTOR_ARGS=("${REACTOR_ARGS[@]}" "--no-cache")
+fi
 
 REACTOR_ARGS=(
   "${REACTOR_ARGS[@]}"
